version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: b363c6c2-94a3-448d-8858-98c6971e3a7d
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
