version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: 6d5df9a3-c14d-47a5-b2d3-78dc644d58ed
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
