version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: fab0abba-901f-4718-91b4-2f54830f213d
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
