version: 1.0
app:
  instances: 
    min: 1
    max: 1
  version: fab0abba-901f-4718-91b4-2f54830f213d
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=prod"
    - name: MAX
      value: "5"
